# Available profiles
#   - none for no profile
#   - crdb-pooling-basic - CockroachDB database with HikariCP. Loads configuration from application-crdb-pooling-basic.properties

spring:
   profiles:
      active: crdb-pooling-basic
