# Available profiles
#   - none for no profile
#   - crdb-pooling-basic - CockroachDB database with HikariCP. Loads configuration from application-crdb-pooling-basic.properties

spring:
resilience4j:
  retry:
  instances:
    transactionRetry:
      max-attempts: 3
      wait-duration: 5s
      enable-exponential-backoff: true
      exponential-backoff-multiplier: 2
      retry-exceptions:
        - java.sql.SQLException